name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 299372338272.dkr.ecr.us-east-1.amazonaws.com

      # - name: Build, tag, and push image to Amazon ECR
      #   run: |
      #     docker build -t mediplus:v1 .
      #     docker tag mediplus:v1 299372338272.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1
      #     docker push 299372338272.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: check my ssh key
        run: 
          echo "${{ secrets.SSH_KEY }}" > mykey.pem
          chmod 600 mykey.pem  
          cat mykey.pem
